config/routes.rb
NonprofitamInfrastructureChecklist::Application.routes.draw do
 
  root :to => 'pages#home' 
  
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

  get "signup" => "users#new", :as => "signup"
  
  resources :responses
  resources :questions
  resources :users
  resources :sessions
  resources :checklists

end

app/models/checklist.rb
class Checklist < ActiveRecord::Base
  attr_accessible :name, :questions_attributes
  
  
  has_many :questions 
  accepts_nested_attributes_for :questions, allow_destroy: true
  
  
  # Public: Counts the integer total amount of questions associated to a given Checklist(n)
  #
  # @hecklist  - A given ActiveRecord Checklist
  # @total - Uses ActiveRecord associations to find number of questions
  #
  # Examples
  #
  #   total_questions(3)
  #   # => 10
  #
  def total_questions
      total =  self.questions.length
      total 
  end
  
  def total_questions_of_priority(priority)
    
    self.questions.where(priority: priority).length
    
  end
  
  def priorities_and_questions
    pq = {"Required" => [], "Strongly Recommended" => [], "Recommended" => []}

    self.questions.each do |q|
      pq[q.priority] << q.id
    end
    pq
  end
  
 
  
  

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :description, :priority
  
  belongs_to :checklist
  
  
  
  
end

app/models/response.rb
class Response < ActiveRecord::Base
  attr_accessible :answers_hash, :user_id, :answer_hash["key"]
  
  serialize(:answers_hash, Hash)
  belongs_to :user
    
  
    # Public: Returns the integer total amount of a given answer(n)
    #
    # a_hash - The ActiveRecord answer_hash of a given response object
    # answers - Array of 'values' for each 'key' in the a_hash
    # count - counts the amount of times a given value[n] is found in "answers"
    #
    # Examples
    #
    #   counts("Yes")
    #   # => 16
    #
    #  counts("No")
    #   # => 3
    #

  def counts(n) 
    count = Hash.new(0)
    a_hash = self.answers_hash
    answers = a_hash.values
    answers.each{ |ans| count[ans] += 1}
    count[n]
  end
  
  
  # Public: Returns a string corresponding to the percentage that a given answer value(value) appears in a given checklist(checklist_id) 
  #
  # value - string that this method looks for (ie. "Yes", "No", "In Progress")
  # checklist_id - id of a Active Record checklist's associated questions that correspond to the keys in a Response object's "answer_hash"
  #
  # This is calculated with the current_user's response object found using the session 
  #     ie current_user.responseid
  #
  # Examples
  #
  #   counts("Yes")
  #   # => 16
  #
  #  counts("No")
  #   # => 3
  #
  
  def percent(value, checklist_id)
    ans = []
    
    Checklist.find(checklist_id).questions.each do |q|
      ans << self.answers_hash["#{q.id}"] 
    end
    count = Hash.new(0)
    ans.each{ |e| count[e] += 1 }
    
    (((count[value].to_f/Checklist.find(checklist_id).total_questions.to_f)*100).to_i).to_s + "%"
   end
   
   def percentage_for_checklist(checklist_id)
     checklist = Checklist.find(checklist_id)
     
     # Hash, keys are priorities and values are question ids
     priorities_and_questions = checklist.priorities_and_questions
     
     priorities_and_questions_answers = {"Required"=>{}, "Strongly Recommended"=>{}, "Recommended"=> {}}
     
     priorities_and_questions.each do |p,qs|
       qs.each do |q|
         priorities_and_questions_answers[p][q]=self.answers_hash[q.to_s]
       end 
     end
     
     priorities_percentages = {
       "Required"=> {"Yes"=> 0, "No"=> 0, "In Progress"=> 0},
       "Strongly Recommended"=> {"Yes"=> 0, "No"=> 0, "In Progress"=> 0},
       "Recommended"=> {"Yes"=> 0, "No"=> 0, "In Progress"=> 0}
     }
     binding.pry
     # priorities_and_questions_answers.each do |p, qa|
   #     qa.each do |q, a|
   #       priorities_percentages[p]["Yes"] = 0
     
    
   end
   
   
     
end

app/models/user.rb
class User < ActiveRecord::Base
   attr_accessible :email, :password, :password_confirmation, :org_name, :admin
  
   has_one :response
  
  
  authenticates_with_sorcery!
  
 
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  
  
  def admin?
    if self.admin == true
      true
    else
      false
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController
  
  def index
    @checklists = Checklist.all
    @user = User.find(current_user.response.id)
  end
  
  def new
    @checklist = Checklist.new
    3.times do
      question = @checklist.questions.build
      
    end
  end
  
  def create 
    @checklist = Checklist.new(params[:checklist])
    if @checklist.save 
      redirect_to checklists_path, :notice => "Checklist created!" 
    else 
      render :new
    end
  end
  
  def edit
    @checklist = Checklist.find(params[:id])
  end
  
  def update 
    @checklist = Checklist.find(params[:id])
      
    if @checklist.update_attributes(params[:checklist])
      redirect_to checklist_path(@checklist.id)
    else
      render :edit
    end
  end
  
  
  def destroy
    @checklist = Checklist.find(params[:id])
    @checklist.delete
    
    redirect_to checklists_path
  end
  
  
  def show 
    @checklist = Checklist.find(params[:id])
  end
  
  
  
  
  
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_filter :authorize
  
  
  def home
  end
  
  
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  
  
  
  def new
    @question = Question.new
   
    respond_to do |format|
      format.js
      format.html
  end
end



end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  
  def index
  end
  
  def new
   
  end

  def create
  
  end

  def edit
    @response = current_user.response
    @checklist = Checklist.find(params[:id])
  end

  def update
    @response = current_user.response
    @response.update_attributes(answers_hash: @response.answers_hash.merge!(params[:spaceship]))
    redirect_to checklists_path
    
  end

  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = login(params[:email], params[:password])
    if user
      redirect_back_or_to checklists_path, :notice => "Logged in!"
    else
      flash.now.alert = "Email or password was invalid"
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
    
  end
  
  def create 
    @user = User.new(params[:user])
    if @user.save
      @user.create_response
      auto_login(@user)
      redirect_to root_url, :notice => "Signed up!"
    else 
      render :new
    end
  end
      
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checklists_helper.rb
module ChecklistsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/checklists/edit.html.erb
<%= form_for @checklist do |f| %>


<%= f.label :name %>
<%= f.text_field :name %>
<br>
    <%= f.fields_for :questions do |builder| %>
  <p>
      <%= builder.label :Question_text %>
      <%= builder.text_area :description %>
    
     
      <%= builder.select :priority ,[['Required', 'Required'], ['Strongly Recommended', 'Strongly Recommended'],['Recommended','Recommended']] %>
      
      <% end %>
</p>

<div class = "question_form"></div>
<%= link_to "Add Question", new_question_path, remote: true %>

  <%= f.submit %>

  <% end %>

app/views/checklists/index.html.erb
<% if current_user == nil %>
<% elsif current_user.admin %>
<h1>Checklists</h1>
<% @checklists.each do |c|%>
  <p>
    <%= link_to c.name, checklist_path(c.id) %>----<%= link_to 'Edit', edit_checklist_path(c.id) %> ----
			<% if c.name ==nil%>
			<% else %> 
				<%= link_to 'Delete', checklist_path(c.id), :action => :post, :method => :delete %>
			<% end %>
  </p>
  <br>
  <br>
<% end %>
  <h3><%= link_to "New Checklist", new_checklist_path %></h3>

<% else %>
<div id='checklists'>
<h2>Click a checklist to fill it out!</h2>
  <% @checklists.each do |c|%>
	<h3>
  	<%= link_to c.name, edit_response_path(c.id), id: c.id %>

		Total Questions: <%= c.total_questions %>
		Yes: <%= Response.find(@user).percent("Yes", c.id) %>
		No: <%= Response.find(@user).percent("No", c.id) %>
		In Progress: <%= Response.find(@user).percent("In Progress", c.id) %>
    
  </h3>
<% end %>
</div>
<% end %>

app/views/checklists/new.html.erb
<%= form_for @checklist do |f| %>


<%= f.label :name %>
<%= f.text_field :name %>
<br>
    <%= f.fields_for :questions do |builder| %>
  <p>
      <%= builder.label :Question_text %>
      <%= builder.text_area :description %>
    
     
      <%= builder.select(:priority, options_for_select([['Required', 'Required'], ['Strongly Recommended', 'Strongly Recommended'],['Recommended','Recommended']]), :prompt => "Priority") %>
  </p>
      <% end %>
      


<div class = "question_form"></div>

<%= link_to "Add Question", new_question_path, remote: true %>

<%= f.submit "Create Listing", :class => 'submit'%>

  <% end %>
  

app/views/checklists/show.html.erb
<h1><%= @checklist.name %></h1>

<% @checklist.questions.each do |q| %>

<p>
  <%= q.description %> ---- <%= q.priority %>
</p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Non-profit Infrastructure Checklist</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
 <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:300' rel='stylesheet' type='text/css'>
 <link href='http://fonts.googleapis.com/css?family=Raleway:500' rel='stylesheet' type='text/css'>
</head>
<body>
  <% if current_user %>
  <p class='current_user'> Hello, <%= current_user.email %>.
    <%= link_to "Log out", logout_path %></p>
  
  <% else %>
    <p class='current_user'><%= link_to "Sign up", signup_path %> or
    <%= link_to "log in", login_path %>.</p>
  <% end %></p>
  

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<div id='logo'> <h1 id="namlogo"> Non-Profit Association of the Midlands</h1></div>

<%if current_user == nil %>
<div id ="login">
<%= form_tag sessions_path do %>
  <div class="field">
    <%= label_tag :email %>
    <br>
    <%= text_field :email, params[:email] %>
  </div>
  <div class="field">
    <%= label_tag :password %>
    <br>
    <%= password_field_tag :password %>
  </div>
  <div class="actions"><%= submit_tag "Log in" %></div>
<% end %>
</div>
<% end %>
<div class='content'>
<h2>About</h2>
<p>This Infrastructure Checklist is a quick guide to the documentation, systems, policies, 
procedures, and support mechanisms that nonprofit organizations should have in 
place to comply with the law, and to function effectively, efficiently, and 
transparently. The Checklist is focused on WHAT YOU SHOULD HAVE IN PLACE rather 
than HOW you should utilize those systems/processes. For the HOW TO, we 
recommend you consult the Guidelines & Principles for Nonprofit Excellence in 
Nebraska & Iowa or the Assessment Tool. </p>
</div>

app/views/questions/_new_question.html.erb
<% x = Time.now.getutc %>
<div class= "question_form_rendered">

<p>
  <%= label_tag "checklist[questions_attributes][#{x}][description]", "Question text"%>
  <%= text_area_tag "checklist[questions_attributes][#{x}][description]", nil, size: "40x20" %>
    
     
  <%= select_tag "checklist[questions_attributes][#{x}][priority]", options_for_select([['Required', 'Required'], ['Strongly Recommended', 'Strongly Recommended'],['Recommended','Recommended']]), :prompt => "Priority" %>

</p>
</div>

app/views/questions/new.html.erb
<h1>Questions#new</h1>
<p>Find me in app/views/questions/new.html.erb</p>

app/views/questions/new.js.erb
$('.question_form').append('<%=j render partial: "new_question" %>');

app/views/responses/create.html.erb
<h1>Responses#create</h1>
<p>Find me in app/views/responses/create.html.erb</p>

app/views/responses/edit.html.erb
<h2><%= @checklist.name %></h2>


<!-- <%= @response.answers_hash.to_a %> -->

<br>
<br>
<%= form_for @response do |f| %>
    
<% priorities = ['Required', 'Strongly Recommended', 'Recommended'] %>
   
<% priorities.each do |p| %>

<h3> <%= p %></h3>
<% @checklist.questions.where(priority: p).each do |q| %>

<table>
  <tr>
    <td>Item: <%= q.description %></td>
    <td>		
      <%= radio_button_tag("spaceship[#{q.id}]", "Yes", (@response.answers_hash["#{q.id}"] == "Yes")) %>
      <%= label_tag(:answers_hash, "Yes") %>
    </td>
    <td>
      <%= radio_button_tag("spaceship[#{q.id}]", "No", (@response.answers_hash["#{q.id}"]== "No")) %>
      <%= label_tag(:answers_hash, "No") %>
    </td>
    <td>
      <%= radio_button_tag("spaceship[#{q.id}]", "In Progress", (@response.answers_hash["#{q.id}"]== "In Progress")) %>
      <%= label_tag(:answers_hash, "In Progress") %>
    </td>
  </tr>
</table>

		  
	
<% end %>
<% end %>

	
<%= f.submit  'Save Checklist', :class => "submit"%>
		
<%end%>
	

app/views/responses/new.html.erb
<h1>Responses#new</h1>
<p>Find me in app/views/responses/new.html.erb</p>

app/views/responses/show.html.erb
<h1>Responses#show</h1>
<p>Find me in app/views/responses/show.html.erb</p>

app/views/responses/update.html.erb
<h1>Responses#update</h1>
<p>Find me in app/views/responses/update.html.erb</p>

app/views/users/new.html.erb
<h1>New User</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <!-- <div class="field">
    <%= f.label :admin? %>
    <%= f.check_box :admin %>
  </div> -->
  
  <div class="actions"><%= f.submit %></div>
<% end %>